server:
  port: 8081

spring:
  application:
    name: module-batch

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://${TRENDING_DB_HOST}:3310/${TRENDING_DB_NAME}?useSSL=false&serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    username: ${TRENDING_DB_USERNAME}
    password: ${TRENDING_DB_PASSWORD}
    hikari:
      pool-name: BatchHikariPool
      maximum-pool-size: 10 #부하테스트하면서 늘릴 예정
      minimum-idle: 5

  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  cloud:
    aws:
      region:
        static: ap-northeast-2
      credentials:
        access-key: dummy-access-key
        secret-key: dummy-secret-key
      sqs:
        endpoint: http://localhost:9324

management:
  endpoints:
    web:
      exposure:
        include: health, info, metrics, prometheus
  metrics:
    tags:
      application: ${spring.application.name}
    enable:
      hikaricp: true # HikariCP 커넥션 풀 메트릭 활성화

app:
  sqs:
    queue-name: task-queue