server:
  port: 8080

spring:
  application:
    name: module-api

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://${TRENDING_DB_HOST}:3310/${TRENDING_DB_NAME}?useSSL=false&serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    username: ${TRENDING_DB_USERNAME}
    password: ${TRENDING_DB_PASSWORD}
    hikari:
      pool-name: ApiHikariPool
      maximum-pool-size: 30 #부하테스트하면서 늘릴 예정
      minimum-idle: 10

  jpa:
    hibernate:
      ddl-auto: none
    show-sql: false #부하테스트를 위해
    properties:
      hibernate:
        format_sql: true
    open-in-view: false # 트랜잭션이 끝나면 커넥션을 풀에 바로 반환 (요청 끝까지 점유하지 않음)

  data:
    redis:
      host: localhost
      port: 6380

  cloud:
    aws:
      region:
        static: ap-northeast-2
      credentials:
        access-key: dummy-access-key
        secret-key: dummy-secret-key
      sqs:
        endpoint: http://localhost:9324

management:
  endpoints:
    web:
      exposure:
        include: health, info, metrics, prometheus
  metrics:
    tags:
      application: ${spring.application.name}
    enable:
      hikaricp: true # HikariCP 커넥션 풀 메트릭 활성화

app:
  queue:
    view-count: post-view-queue
    like-count: post-like-queue